modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Buwwet/TinyBlocks"
license = "Insert License Here"

[[mods]]
modId = "tinyblocks"
version = "${version}"
displayName = "TinyBlocks"
authors = "Buwwet"
description = '''
A mod that adds support for building interactive structures at 1/4 of the normal scale.
'''
#logoFile = ""

[[dependencies.tinyblocks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyblocks]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"